### ISSUE TITLE
每次触发时会清空 oss bucket 的镜像回源配置

### ISSUE THREAD

**Issue by Wzb3422** [fangbinwei/aliyun-oss-website-action#1]
因为我部署的是 Vue 项目，使用的是 Vue-router 的 history 模式。需要配置阿里云 OSS 镜像回源规则来避免刷新之后 404 的问题。
然而，每次调用 aliyun-oss-website-action 之后，都会将我的 bucket 配置的镜像回源规则清空。

附使用的 GitHub Action 配置：
```yml
name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build project
      run: |
        echo install dependencies
        npm i
        echo build project
        npm run build

    - name: upload files to OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.ACCESSKEYID }}
          accessKeySecret: ${{ secrets.ACCESSKEYSECRET }}
          bucket: ncuos-fe
          endpoint: oss-cn-hangzhou.aliyuncs.com
          folder: dist
```
